# Base image with Amazon Corretto JDK 21
FROM amazoncorretto:21

# Set working directory
WORKDIR /app

# Copy JAR file to the container
COPY build/libs/noostak-0.0.1-SNAPSHOT.jar /app/noostak.jar

# Expose default Spring Boot port
EXPOSE 8080

# Run the application
CMD ["java", "-Duser.timezone=Asia/Seoul", "-jar", "-Dspring.profiles.active=prod", "noostak.jar"]
