name: DOCKER-CD-STAGING

on:
  pull_request:
    branches: [ "staging" ]

jobs:
  ci:
    # Using Environment - prod 환경 사용
    # environment: prod
    runs-on: ubuntu-24.04
    env:
      working-directory: .

    # Checkout - 가상 머신에 체크아웃
    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      # remote branch에서 pull
      - name: Pull specific branch
        run: |
            git checkout staging
            git pull origin staging
              # remote branch에서 pull
        working-directory: ${{ env.working-directory }}


      # JDK setting - Amazon Corretto JDK 21 설정
      - name: Set up Amazon Corretto JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      # Gradle caching - 빌드 시간 향상
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: application.yml 생성
        run: |
          mkdir -p ./src/main/resources && cd $_
          touch ./application.yml
          echo "${{ secrets.YML }}" > ./application.yml
          cat ./application.yml
        working-directory: ${{ env.working-directory }}

      - name: application-staging.yml 생성
        run: |
          cd ./src/main/resources
          touch ./application-staging.yml
          echo "${{ secrets.PROD_STAGING }}" > ./application-staging.yml
        working-directory: ${{ env.working-directory }}

      - name: aws-config.yml 생성
        run: |
          cd ./src/main/resources
          touch ./aws-config.yml
          echo "${{ secrets.AWS_CONFIG_YML }}" > ./aws-config.yml
        working-directory: ${{ env.working-directory }}

      - name: oauth-config.yml 생성
        run: |
          cd ./src/main/resources
          touch ./oauth-config.yml
          echo "${{ secrets.STAGING_OAUTH_CONFIG_YML }}" > ./oauth-config.yml
        working-directory: ${{ env.working-directory }}

      - name: 빌드
        run: |
          chmod +x gradlew
          ./gradlew build -x test
        working-directory: ${{ env.working-directory }}
        shell: bash

      - name: docker 로그인
        uses: docker/setup-buildx-action@v2.9.1

      - name: login docker hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.STAGING_DOCKER_LOGIN_USERNAME }}
          password: ${{ secrets.STAGING_DOCKER_LOGIN_ACCESSTOKEN }}

      - name: docker image 빌드 및 푸시
        run: |
          docker build -f Dockerfile-staging --platform linux/amd64 -t noostak/staging .
          docker push noostak/staging
        working-directory: ${{ env.working-directory }}

  cd:
    needs: ci
    runs-on: ubuntu-24.04

    steps:
      - name: docker 컨테이너 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ${{ secrets.STAGING_SERVER_USER }}
          key: ${{ secrets.STAGING_SERVER_KEY }}
          script: |
            cd ~
            ./deploy-staging.sh
